language: c++
compiler: gcc

os: linux
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake-data
      - cmake
      - libgtest-dev
      - libboost-dev
      - doxygen
      - libprotobuf-dev
      - openssl
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
install:
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz
  - cd kcov-master
  - mkdir build
  - cd build
  - cmake ..
  - make
  # puts kcov in the default location usually /usr/local/bin/kcov
  - make install

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - ./bin/Borderlands2SaveLibTest

after_success:
  - mkdir cov
  - /usr/local/bin/kcov --exclude-path=/usr/ --exclude-pattern=.pb.,minilzo,autogen --coveralls-id=$TRAVIS_JOB_ID  --verify cov/ bin/Borderlands2SaveLibTest